version: '3.7'

volumes:
    redis_data:
        external: true
    paymentMongoData:
        external: true
networks:
    int-network:
        external: true

services:

    paymentmongo:
        image: mongo:4.4
        container_name: paymentmongo
        restart: always
        networks:
            - int-network
        volumes:
            - paymentMongoData:/data/db
            - ./data:/backup
        ports:
            - "27024:27017"

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASS}
            MONGO_INITDB_DATABASE: ${MONGODB}


    paymentsystem:
        container_name: paymentsystem
        networks:
            - int-network
        user: root
        build:
            context: .
        ports:
            - "3001:3004"
            - "3003:3003" #
        restart: always
