version: '3.7'

volumes:
    redis_data:
        external: true
    paymentMongoData:
        external: true
    paymentMongoProdData:
            external: true
networks:
    int-network:
        external: true

services:

    paymentmongo:
        image: mongo:4.4
        container_name: ${CONTAINER_MONGO_NAME}
        restart: always
        networks:
            - int-network
        volumes:
            - ${PAYMENT_VOLUME}:/data/db
            - ./data:/backup
        ports:
            - "27024:27017"

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASS}
            MONGO_INITDB_DATABASE: ${MONGODB}


    paymentsystem:
        container_name: ${CONTAINER_PAYMENT_NAME}
        networks:
            - int-network
        user: root
        build:
            context: .
        ports:
            - ${MAINPORT}:${MAINPORT}
            - ${MICROPORT}:${MICROPORT}
        restart: always
